name: budgetplanner
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.0.11+11

environment:
  sdk: ">=2.12.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_cupertino_localizations: 1.0.1
  #page_transition: ^2.0.2
  eva_icons_flutter: ^3.0.0
  google_fonts: ^2.0.0
  hive: ^2.0.4
  #flutter_rounded_date_picker: 2.0.2 // circular date picker dialog
  intl: ^0.17.0
  super_tooltip: ^1.0.1
  sleek_circular_slider: ^2.0.0
  currency_picker: ^2.0.3

  get: ^4.1.4

  # lib. to manage firebase config.
  firebase_core: ^1.2.1
  cloud_firestore: ^2.2.1
  firebase_auth: ^1.4.1
  google_sign_in: ^5.0.4
  firebase_dynamic_links: ^2.0.6

  # lib. to manage http call and state managemnet using bloc pattern
  retrofit: ^2.0.0
  logger: any
  dio: ^4.0.0
  json_annotation: ^4.0.1
  flutter_bloc: ^7.0.0
  equatable: ^2.0.0
  pretty_dio_logger: ^1.1.1
  shared_preferences: ^2.0.6
  synchronized:

  charts_flutter: ^0.11.0
  grouped_list: ^4.0.0
  share: ^2.0.4
  shimmer: ^2.0.0
  google_mobile_ads: ^0.13.2
  package_info: ^2.0.2
  csv: ^5.0.0
  path_provider: ^2.0.2
  flutter_local_notifications: ^6.0.0
  open_file: ^3.2.1
  permission_handler: ^8.1.2
  fl_chart: ^0.36.2
  

dependency_overrides:
  retrofit_generator:
    git:
      url: https://github.com/Chimerapps/retrofit.dart.git
      ref: 9f90296751984b359937c38563da5b19db5550f5
      path: generator  
  


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  analyzer: ^1.5.0
  retrofit_generator: ^2.0.0
  build_runner: any
  json_serializable: ^4.1.1
  source_gen: ^1.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
