name: budgetplanner
description: A new Flutter project.



publish_to: 'none' 











version: 0.0.22+22

environment:
  sdk: ">=2.12.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_cupertino_localizations: 1.0.1
  
  eva_icons_flutter: ^3.0.0
  google_fonts: ^2.0.0
  
  intl: ^0.17.0
  sleek_circular_slider: ^2.0.0
  currency_picker: ^2.0.3

  get: ^4.1.4

  
  firebase_core: ^1.6.0
  cloud_firestore: ^3.1.0
  firebase_auth: ^3.1.1
  google_sign_in: ^5.1.0
  

  
  logger: any
  json_annotation: ^4.0.1
  shared_preferences: ^2.0.6
  synchronized:

  grouped_list: ^4.1.0
  share: ^2.0.4
  shimmer: ^2.0.0
  google_mobile_ads: ^1.0.0
  package_info: ^2.0.2
  csv: ^5.0.0
  path_provider: ^2.0.2
  flutter_local_notifications: ^9.0.0
  open_file: ^3.2.1
  permission_handler: ^9.2.0
  fl_chart: ^0.50.1
  flutter_native_timezone: ^2.0.0
  collection: ^1.15.0
  workmanager: ^0.4.1
  cached_network_image: ^3.1.0
  url_launcher: ^6.0.12

  camera:
  path:

  
  
  cupertino_icons: ^1.0.3



  
dev_dependencies:
  flutter_test:
    sdk: flutter
  analyzer: ^4.0.0
  build_runner: any
  json_serializable: ^6.0.1
  source_gen: ^1.0.1
  





flutter:

  
  
  
  uses-material-design: true

  
  assets:
    - assets/
    - assets/images/
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
