import 'package:budgetplanner/screens/bottom_nav/pages/transaction/add_income.dart';

const String name = "name";
const String id = "id";
const String email = "email";
const String transactionEntry = "Add Transaction";
const amount = "Amount";
const notes = "Notes";
const recurrance = "Recurrance";
const select_expense_category = "Waht are you expending for?";
const select_income_source = "Select income source";
const select_expense_source = "Select expense source";
const def_recurrance = "Never";
const def_source = "Cash";
const def_notes = "Adding notes give you more clarity of the transaction";
const homeTab = "Home";
const transactionTab = "Transaction";
const addTab = "Add";
const statsTab = "Stats";
const settingsTab = "Settings";
const addIncome = "Add Income";
const addExpense = "Add Expense";
