import 'package:budgetplanner/utils/string_constants.dart';

const bn = {
  total_income: "আয়",
  total_expense: "ব্যয়",
  total_balance: "ভারসাম্য",
  recent_transaction: "সাম্প্রতিক লেনদেন",
  homeTab: "বাড়ি",
  transactionTab: "লেনদেন",
  addTab: "অ্যাড",
  budgetTab: "বাজেট",
  settingsTab: "সেটিংস",
  yesterday: "গতকাল",
  today: "আজ",
  update_your_daily: "আপনার প্রতিদিন আপডেট করুন",
  update: "হালনাগাদ",
  lbl_trx_not_updated: "উফফফফ !!! ... লেনদেন আপডেট হয়নি!",
  lbl_trx_updated: "লেনদেন সফলভাবে আপডেট হয়েছে!",
  lbl_income_source: "ব্যয় উত্স নির্বাচন করুন",
  lbl_trx_cancelled: "ওফফফ !!! ... লেনদেন বাতিল!",
  lbl_trx_success: "লেনদেন সফলভাবে শেষ হয়েছে!",
  lbl_amount_error: "পরিমাণ লিখুন দয়া করে",
  lbl_notes_error: "নোটগুলি অবশ্যই 6 টি বর্ণের হতে হবে",
  transactionEntry: "লেনদেন যুক্ত করুন",
  addExpense: "ব্যয় যুক্ত করুন",
  select_expense_category: "আপনি কি জন্য ব্যয় করছেন?",
  amount: "পরিমাণ",
  notes: "মন্তব্য",
  select_expense_source: "ব্যয় উত্স নির্বাচন করুন",
  expense_type: "ব্যয়ের ধরণ",
  want_or_need: "চাই/দরকার",
  recurrance: "পুনরাবৃত্তি",
  addIncome: "আয় যোগ করুন",
  select_income_source: "আয়ের উত্স নির্বাচন করুন",
  plan_month: "আপনার মাসিক পরিকল্পনা করুন",
  addBudget: "বাজেট যুক্ত করুন",
  select_budget_category: "বাজেট বিভাগ নির্বাচন করুন",
  monthName: "মাসের নাম",
  update_plan_month: "আপনার মাসিক আপডেট করুন",
  updateBudget: "বাজেট আপডেট করুন",
  lbl_budget_not_update: "উফফফফ !!! ... বাজেট আপডেট হয়নি!",
  lbl_budget_update: "বাজেট সফলভাবে আপডেট হয়েছে!",
  lbl_budget_not_delete: "উফফফফ !!! ... বাজেট মোছা হয়নি!",
  lbl_budget_delete_success: "সফলভাবে মুছে ফেলা হয়েছে!",
  lbl_budget_not_saved: "উফস !!! ... বাজেট সংরক্ষণ করা হয়নি",
  lbl_budget_save_success: "বাজেট সাফল্যের সাথে সংরক্ষণ করা হয়েছে!",
  lbl_select_budget_cat: "বাজেট বিভাগ নির্বাচন করুন",
  lbl_income_source_error: "আয়ের উত্স নির্বাচন করুন",
  lbl_trx_not_delete: "উফফফফ !!! ... লেনদেন মোছা হয়নি!",
  //new translation
  lbl_no_budget: "প্রতি মাসে অর্থ ফুরিয়েছে",
  desc_no_budget:
      "প্রতি ডলার কোথায় যায় তা দেখা শুরু করার এবং আপনার আর্থিক লক্ষ্যের জন্য আরও শৃঙ্খলা তৈরি করার সময়।",
  lbl_add_one: "এক যোগ কর",
  lbl_no_transaction: "সর্বদা আপনার লেনদেনের একটি রেকর্ড করুন",
  desc_no_transaction:
      "এটি আপনাকে আর্থিকভাবে সুশৃঙ্খল করে তোলে এবং আপনার আর্থিক স্বাস্থ্যের উত্সাহ দেয়।",
  lbl_config_laguage: "আপনার অঞ্চলটি কনফিগার করুন",
  lbl_language: "ভাষা",
  lbl_request_feature: "নতুন জন্য অনুরোধ",
  lbl_feature: "বৈশিষ্ট্য",
  lbl_settings_cutomise: "আপনার অ্যাপ্লিকেশনটি কাস্টমাইজ করুন",
  feature_request: "আপনার প্রয়োজনীয়তা ব্যাখ্যা করুন",
  submit: "জমা দিন",
  lbl_history: "রিপোর্ট",
  monthly_budget: "মাসিক বাজেট",
};
