import 'package:budgetplanner/utils/string_constants.dart';

const de = {
  total_income: "Einkommen",
  total_expense: "Aufwand",
  total_balance: "Balance",
  recent_transaction: "Kürzliche Transaktionen",
  homeTab: "Zuhause",
  transactionTab: "Transaktion",
  addTab: "Hinzufügen",
  budgetTab: "Budget",
  settingsTab: "die Einstellungen",
  yesterday: "Gestern",
  today: "Heute",
  update_your_daily: "Aktualisieren Sie Ihre tägliche",
  update: "Aktualisieren",
  lbl_trx_not_updated: "Hoppla!!!...Transaktion nicht aktualisiert!",
  lbl_trx_updated: "Transaktion erfolgreich aktualisiert!",
  lbl_income_source: "Bitte Kostenquelle auswählen",
  lbl_trx_cancelled: "Hoppla!!!...Transaktion abgebrochen!",
  lbl_trx_success: "Transaktion erfolgreich abgeschlossen!",
  lbl_amount_error: "Bitte Betrag eingeben",
  lbl_notes_error: "Notizen müssen aus 6 Zeichen bestehen",
  transactionEntry: "Transaktion hinzufügen",
  addExpense: "Ausgaben hinzufügen",
  select_expense_category: "Wofür gibst du aus?",
  amount: "Menge",
  notes: "Anmerkungen",
  select_expense_source: "Kostenquelle auswählen",
  expense_type: "Kostenart",
  want_or_need: "Wollen/Brauchen",
  recurrance: "Wiederholung",
  addIncome: "Einkommen hinzufügen",
  select_income_source: "Einkommensquelle auswählen",
  plan_month: "Planen Sie Ihren Monat",
  addBudget: "Budget hinzufügen",
  select_budget_category: "Budgetkategorie auswählen",
  monthName: "Monatsname",
  update_plan_month: "Aktualisieren Sie Ihren Monat",
  updateBudget: "Budget aktualisieren",
  lbl_budget_not_update: "Hoppla!!!...Budget nicht aktualisiert!",
  lbl_budget_update: "Budget erfolgreich aktualisiert!",
  lbl_budget_not_delete: "Hoppla!!!...Budget nicht gelöscht!",
  lbl_budget_delete_success: "Erfolgreich gelöscht!",
  lbl_budget_not_saved: "Hoppla!!!...Budget nicht gespeichert",
  lbl_budget_save_success: "Budget erfolgreich gespeichert!",
  lbl_select_budget_cat: "Bitte Budgetkategorie auswählen",
  lbl_income_source_error: "Bitte Einkommensquelle auswählen",
  lbl_trx_not_delete: "Hoppla!!!...Transaktion nicht gelöscht!",
  lbl_no_budget: "Jeden Monat geht das Geld aus",
  desc_no_budget:
      "Es ist an der Zeit, zu beobachten, wohin jeder Dollar geht und mehr Disziplin für Ihre finanziellen Ziele aufzubauen.",
  lbl_add_one: "Füge eins hinzu",
  lbl_no_transaction: "Machen Sie immer eine Aufzeichnung Ihrer Transaktion",
  desc_no_transaction:
      "Es macht Sie finanziell diszipliniert und stärkt Ihre finanzielle Gesundheit.",
  lbl_config_laguage: "Konfigurieren Sie Ihre Region",
  lbl_language: "Sprache",
  lbl_request_feature: "Anfrage für neue",
  lbl_feature: "Feature",
  lbl_settings_cutomise: "Passen Sie Ihre App an",
  feature_request: "Bitte erläutern Sie Ihre Anforderungen",
  submit: "einreichen",
  lbl_history: "Berichte",
  monthly_budget: "Monatliches Budget",
  lbl_exit_message: "Sie sind sicher, dass Sie beenden wollen?",
  lbl_no: "Nein",
  lbl_yes: "Ausgang",
};
