import 'package:budgetplanner/utils/string_constants.dart';

const en = {
  total_income: "Income",
  total_expense: "Expense",
  total_balance: "Balance",
  recent_transaction: "Recent transactions",
  homeTab: "Home",
  transactionTab: "Transaction",
  addTab: "Add",
  budgetTab: "Budget",
  settingsTab: "Settings",
  yesterday: "Yesterday",
  today: "Today",
  update_your_daily: "Update your daily",
  update: "Update",
  lbl_trx_not_updated: "Ooops!!!...transaction not updated!",
  lbl_trx_updated: "Transaction updated successfully!",
  lbl_income_source: "Please select expense source",
  lbl_trx_cancelled: "Ooops!!!...transaction cancelled!",
  lbl_trx_success: "Transaction completed successfully!",
  lbl_amount_error: "Please enter amount",
  lbl_notes_error: "Notes must be of 6 characters",
  transactionEntry: "Add Transaction",
  addExpense: "Add Expense",
  select_expense_category: "What are you spending for?",
  amount: "Amount",
  notes: "Notes",
  select_expense_source: "Select expense source",
  expense_type: "Expense type",
  want_or_need: "Want/Need",
  recurrance: "Recurrence",
  addIncome: "Add Income",
  select_income_source: "Select income source",
  plan_month: "Plan your monthly",
  addBudget: "Add Budget",
  select_budget_category: "Select budget category",
  monthName: "Month name",
  update_plan_month: "Update your monthly",
  updateBudget: "Update Budget",
  lbl_budget_not_update: "Ooops!!!...budget not updated!",
  lbl_budget_update: "Budget updated successfully!",
  lbl_budget_not_delete: "Ooops!!!...budget not deleted!",
  lbl_budget_delete_success: "Deleted Successfully!",
  lbl_budget_not_saved: "Ooops!!!...Budget not saved",
  lbl_budget_save_success: "Budget saved successfully!",
  lbl_select_budget_cat: "Please select budget category",
  lbl_income_source_error: "Please select income source",
  lbl_trx_not_delete: "Ooops!!!...transaction not deleted!",
  //new translation
  lbl_no_budget: "Running out of money every month",
  desc_no_budget:
      "Time to start watching where every dollar goes & build more discipline for your financial goals.",
  lbl_add_one: "Add One",
  lbl_no_transaction: "Always make a record of your transaction",
  desc_no_transaction:
      "It's makes you financially disciplined and boost your financial health.",
  lbl_config_laguage: "Config your region",
  lbl_language: "Language",
  lbl_request_feature: "Request for new",
  lbl_feature: "Feature",
  lbl_settings_cutomise: "Customise your app",
  feature_request: "Please explain your requirements",
  submit: "Submit",
  lbl_history: "Reports",
  monthly_budget: "Monthly budget",
  lbl_exit_message: "Are you sure you want to exit?",
  lbl_no: "No",
  lbl_yes: "Yes, Exit",
  lbl_delete_message: "Are you sure you want to delete ?",
  cancel: "Cancel",
  delete: "Delete",
};
