import 'package:budgetplanner/utils/string_constants.dart';

const es = {
  total_income: "Ingreso",
  total_expense: "Gastos",
  total_balance: "Equilibrio",
  recent_transaction: "Transacciones Recientes",
  homeTab: "Casa",
  transactionTab: "Transacción",
  addTab: "Agregar",
  budgetTab: "Presupuesto",
  settingsTab: "Ajustes",
  yesterday: "Ayer",
  today: "Hoy",
  update_your_daily: "Actualiza tu diario",
  update: "Actualizar",
  lbl_trx_not_updated: "Ooops !!! ... transacción no actualizada!",
  lbl_trx_updated: "¡Transacción actualizada correctamente!",
  lbl_income_source: "Seleccione la fuente de gastos",
  lbl_trx_cancelled: "Ooops !!! ... Transacción cancelada!",
  lbl_trx_success: "¡Transacción completada con éxito!",
  lbl_amount_error: "Por favor ingrese la cantidad",
  lbl_notes_error: "Las notas deben tener 6 caracteres",
  transactionEntry: "Agregar transacción",
  addExpense: "Agregar gasto",
  select_expense_category: "¿Para qué estás gastando?",
  amount: "Monto",
  notes: "Notas",
  select_expense_source: "Seleccionar fuente de gastos",
  expense_type: "Tipo de gasto",
  want_or_need: "Querer/Necesitar",
  recurrance: "Reaparición",
  addIncome: "Agregar ingresos",
  select_income_source: "Seleccionar fuente de ingresos",
  plan_month: "Planifica tu mensual",
  addBudget: "Agregar presupuesto",
  select_budget_category: "Seleccionar categoría de presupuesto",
  monthName: "Nombre del mes",
  update_plan_month: "Actualice su mensual",
  updateBudget: "Actualizar presupuesto",
  lbl_budget_not_update: "Ooops !!! ... presupuesto no actualizado!",
  lbl_budget_update: "¡Presupuesto actualizado con éxito!",
  lbl_budget_not_delete: "Vaya !!! ... presupuesto no eliminado!",
  lbl_budget_delete_success: "¡Borrado exitosamente!",
  lbl_budget_not_saved: "Ooops !!! ... Presupuesto no guardado",
  lbl_budget_save_success: "¡Presupuesto guardado correctamente!",
  lbl_select_budget_cat: "Seleccione una categoría de presupuesto",
  lbl_income_source_error: "Seleccione la fuente de ingresos",
  lbl_trx_not_delete: "Ooops !!! ... transacción no eliminada!",
};
