import 'package:budgetplanner/utils/string_constants.dart';

const hi = {
  total_income: "आय",
  total_expense: "खर्च",
  total_balance: "बचत",
  recent_transaction: "हाल ही के लेनदेन",
  homeTab: "होम",
  transactionTab: "लेन-देन",
  addTab: "जोड़े",
  budgetTab: "बजट",
  settingsTab: "सेटिंग्स",
  yesterday: "बिता कल",
  today: "आज",
  update_your_daily: "अपना दैनिक अपडेट करें",
  update: "अपडेट करें",
  lbl_trx_not_updated: "ओह!...लेनदेन अद्यतन नहीं!",
  lbl_trx_updated: "लेन-देन सफलतापूर्वक अपडेट किया गया!",
  lbl_income_source: "कृपया व्यय स्रोत का चयन करें",
  lbl_trx_cancelled: "ओह!...लेनदेन रद्द!",
  lbl_trx_success: "लेन-देन सफलतापूर्वक पूरा हुआ!",
  lbl_amount_error: "कृपया राशि दर्ज करें",
  lbl_notes_error: "नोट्स 6 वर्णों के होने चाहिए",
  transactionEntry: "लेन-देन जोड़ें",
  addExpense: "व्यय जोड़ें",
  select_expense_category: "आप किस लिए खर्च कर रहे हैं?",
  amount: "राशि",
  notes: "नोट्स",
  select_expense_source: "व्यय स्रोत का चयन करें",
  expense_type: "व्यय प्रकार",
  want_or_need: "इच्छा/जरुरत",
  recurrance: "पुनरावृत्ति",
  addIncome: "आय जोड़ें",
  select_income_source: "आय का स्रोत चुनें",
  plan_month: "अपनी मासिक योजना बनाएं",
  addBudget: "बजट जोड़ें",
  select_budget_category: "बजट श्रेणी चुनें",
  monthName: "महीने का नाम",
  update_plan_month: "अपना मासिक अपडेट करें",
  updateBudget: "बजट अपडेट",
  lbl_budget_not_update: "ओह!...बजट अपडेट नहीं हुआ!",
  lbl_budget_update: "बजट सफलतापूर्वक अपडेट किया गया!",
  lbl_budget_not_delete: "ओह!...बजट हटाया नहीं गया!",
  lbl_budget_delete_success: "सफलतापूर्वक मिटाया गया!",
  lbl_budget_not_saved: "ओह!...बजट सहेजा नहीं गया",
  lbl_budget_save_success: "बजट सफलतापूर्वक सहेजा गया!",
  lbl_select_budget_cat: "कृपया बजट श्रेणी चुनें",
  lbl_income_source_error: "कृपया आय का स्रोत चुनें",
  lbl_trx_not_delete: "ओह!...लेनदेन हटाया नहीं गया!",
  lbl_no_budget: "हर महीने पैसे से बाहर चल रहा है",
  desc_no_budget:
      "यह देखना शुरू करने का समय है कि हर रुपया कहां जाता है और अपने वित्तीय लक्ष्यों के लिए अधिक अनुशासन का निर्माण करें।",
  lbl_add_one: "एक जोड़ें",
  lbl_no_transaction: "हमेशा अपने लेन-देन का रिकॉर्ड बनाएं",
  desc_no_transaction:
      "यह आपको आर्थिक रूप से अनुशासित बनाता है और आपके वित्तीय स्वास्थ्य को बढ़ावा देता है।",
  lbl_config_laguage: "अपने क्षेत्र को कॉन्फ़िगर करें",
  lbl_language: "भाषा",
  lbl_request_feature: "नए के लिए अनुरोध",
  lbl_feature: "फ़ीचर",
  lbl_settings_cutomise: "अपना ऐप कस्टमाइज़ करें",
  feature_request: "कृपया अपनी आवश्यकताओं की व्याख्या करें",
  submit: "प्रस्तुत",
  lbl_history: "विवरण",
  monthly_budget: "महीने का हिसाब - किताब",
  lbl_exit_message: "क्या आप बाहर निकलना चाहते हैं?",
  lbl_no: "नहीं",
  lbl_yes: "हाँ, बाहर",
};
