import 'package:budgetplanner/utils/string_constants.dart';

const hi = {
  total_income: "आय",
  total_expense: "खर्च",
  total_balance: "बचत",
  recent_transaction: "हाल ही के लेनदेन",
  homeTab: "होम",
  transactionTab: "लेन-देन",
  addTab: "जोड़े",
  budgetTab: "बजट",
  settingsTab: "सेटिंग्स",
  yesterday: "बिता कल",
  today: "आज",
  update_your_daily: "अपना दैनिक अपडेट करें",
  update: "अपडेट करें",
  lbl_trx_not_updated: "ओह!...लेनदेन अद्यतन नहीं!",
  lbl_trx_updated: "लेन-देन सफलतापूर्वक अपडेट किया गया!",
  lbl_income_source: "कृपया व्यय स्रोत का चयन करें",
  lbl_trx_cancelled: "ओह!...लेनदेन रद्द!",
  lbl_trx_success: "लेन-देन सफलतापूर्वक पूरा हुआ!",
  lbl_amount_error: "कृपया राशि दर्ज करें",
  lbl_notes_error: "नोट्स 6 वर्णों के होने चाहिए",
  transactionEntry: "लेन-देन जोड़ें",
  addExpense: "व्यय जोड़ें",
  select_expense_category: "आप किस लिए खर्च कर रहे हैं?",
  amount: "राशि",
  notes: "नोट्स",
  select_expense_source: "व्यय स्रोत का चयन करें",
  expense_type: "व्यय प्रकार",
  want_or_need: "इच्छा/जरुरत",
  recurrance: "पुनरावृत्ति",
  addIncome: "आय जोड़ें",
  select_income_source: "आय का स्रोत चुनें",
  plan_month: "अपनी मासिक योजना बनाएं",
  addBudget: "बजट जोड़ें",
  select_budget_category: "बजट श्रेणी चुनें",
  monthName: "महीने का नाम",
  update_plan_month: "अपना मासिक अपडेट करें",
  updateBudget: "बजट अपडेट",
  lbl_budget_not_update: "ओह!...बजट अपडेट नहीं हुआ!",
  lbl_budget_update: "बजट सफलतापूर्वक अपडेट किया गया!",
  lbl_budget_not_delete: "ओह!...बजट हटाया नहीं गया!",
  lbl_budget_delete_success: "सफलतापूर्वक मिटाया गया!",
  lbl_budget_not_saved: "ओह!...बजट सहेजा नहीं गया",
  lbl_budget_save_success: "बजट सफलतापूर्वक सहेजा गया!",
  lbl_select_budget_cat: "कृपया बजट श्रेणी चुनें",
  lbl_income_source_error: "कृपया आय का स्रोत चुनें",
  lbl_trx_not_delete: "ओह!...लेनदेन हटाया नहीं गया!",
};
