import 'package:budgetplanner/utils/string_constants.dart';

const it = {
  total_income: "Reddito",
  total_expense: "Spese",
  total_balance: "Equilibrio",
  recent_transaction: "Le transazioni recenti",
  homeTab: "Casa",
  transactionTab: "Transazione",
  addTab: "Inserisci",
  budgetTab: "Budget",
  settingsTab: "impostazioni",
  yesterday: "Ieri",
  today: "Oggi",
  update_your_daily: "Aggiorna il tuo quotidiano",
  update: "Aggiornare",
  lbl_trx_not_updated: "Ooops!!!...transazione non aggiornata!",
  lbl_trx_updated: "Transazione aggiornata con successo!",
  lbl_income_source: "Si prega di selezionare la fonte di spesa",
  lbl_trx_cancelled: "Ooops!!!... transazione annullata!",
  lbl_trx_success: "Transazione completata con successo!",
  lbl_amount_error: "Si prega di inserire l'importo",
  lbl_notes_error: "Le note devono essere di 6 caratteri",
  transactionEntry: "Aggiungi transazione",
  addExpense: "Aggiungi spesa",
  select_expense_category: "Per cosa stai spendendo?",
  amount: "Quantità",
  notes: "Appunti",
  select_expense_source: "Seleziona la fonte di spesa",
  expense_type: "Tipo di spesa",
  want_or_need: "Volere/Bisogno",
  recurrance: "Ricorrenza",
  addIncome: "Aggiungi reddito",
  select_income_source: "Seleziona la fonte di reddito",
  plan_month: "Organizza il tuo mensile",
  addBudget: "Aggiungi budget",
  select_budget_category: "Seleziona la categoria di budget",
  monthName: "Nome del mese",
  update_plan_month: "Aggiorna il tuo mensile",
  updateBudget: "Aggiorna budget",
  lbl_budget_not_update: "Ops!!!...budget non aggiornato!",
  lbl_budget_update: "Budget aggiornato con successo!",
  lbl_budget_not_delete: "Ooops!!!...il budget non è stato cancellato!",
  lbl_budget_delete_success: "Eliminato con successo!",
  lbl_budget_not_saved: "Ops!!!...Budget non salvato",
  lbl_budget_save_success: "Budget salvato con successo!",
  lbl_select_budget_cat: "Si prega di selezionare la categoria di budget",
  lbl_income_source_error: "Si prega di selezionare la fonte di reddito",
  lbl_trx_not_delete: "Ooops!!!...transazione non cancellata!",
  //new translation
  lbl_no_budget: "A corto di soldi ogni mese",
  desc_no_budget:
      "È ora di iniziare a guardare dove va ogni dollaro e costruire più disciplina per i tuoi obiettivi finanziari.",
  lbl_add_one: "Aggiungi uno",
  lbl_no_transaction: "Registra sempre la tua transazione",
  desc_no_transaction:
      "Ti rende finanziariamente disciplinato e aumenta la tua salute finanziaria.",
  lbl_config_laguage: "Configura la tua regione",
  lbl_language: "linguaggio",
  lbl_request_feature: "Richiesta di nuovo",
  lbl_feature: "Caratteristica",
  lbl_settings_cutomise: "Personalizza la tua app",
  feature_request: "Si prega di spiegare le vostre esigenze",
  submit: "Invia",
  lbl_history: "Rapporti",
  monthly_budget: "Budget mensile",
};
