import 'package:budgetplanner/utils/string_constants.dart';

const ja = {
  total_income: "所得",
  total_expense: "費用",
  total_balance: "残高",
  recent_transaction: "最近の取引",
  homeTab: "ホーム",
  transactionTab: "トランザクション",
  addTab: "追加",
  budgetTab: "予算",
  settingsTab: "設定",
  yesterday: "昨日",
  today: "今日",
  update_your_daily: "毎日更新する",
  update: "更新",
  lbl_trx_not_updated: "おっと!!! ...トランザクションは更新されていません！",
  lbl_trx_updated: "トランザクションが正常に更新されました。",
  lbl_income_source: "経費源を選択してください",
  lbl_trx_cancelled: "おっと!!! ...トランザクションがキャンセルされました！",
  lbl_trx_success: "トランザクションが正常に完了しました。",
  lbl_amount_error: "金額を入力してください",
  lbl_notes_error: "メモは6文字である必要があります",
  transactionEntry: "トランザクションの追加",
  addExpense: "経費を追加する",
  select_expense_category: "あなたは何のために使っていますか？",
  amount: "量",
  notes: "ノート",
  select_expense_source: "経費源を選択する",
  expense_type: "経費タイプ",
  want_or_need: "欲しいです/必要",
  recurrance: "再発",
  addIncome: "収入を追加する",
  select_income_source: "収入源を選択する",
  plan_month: "毎月の計画",
  addBudget: "予算を追加する",
  select_budget_category: "予算カテゴリを選択",
  monthName: "月名",
  update_plan_month: "毎月更新",
  updateBudget: "予算を更新する",
  lbl_budget_not_update: "おっと!!! ...予算は更新されていません！",
  lbl_budget_update: "予算が正常に更新されました！",
  lbl_budget_not_delete: "おっと!!! ...予算は削除されません！",
  lbl_budget_delete_success: "正常に削除されました！",
  lbl_budget_not_saved: "おっと!!! ...予算が保存されていません",
  lbl_budget_save_success: "予算の節約に成功しました！",
  lbl_select_budget_cat: "予算カテゴリを選択してください",
  lbl_income_source_error: "収入源を選択してください",
  lbl_trx_not_delete: "おっと!!! ...トランザクションは削除されません！",
  //new translation
  lbl_no_budget: "毎月お金が足りなくなる",
  desc_no_budget: "すべてのドルがどこに行くのかを見始めて、あなたの財政目標のためにより多くの規律を構築する時が来ました。",
  lbl_add_one: "1つ追加",
  lbl_no_transaction: "常に取引の記録を作成してください",
  desc_no_transaction: "それはあなたを財政的に訓練させ、あなたの財政状態を後押しします。",
  lbl_config_laguage: "地域を構成する",
  lbl_language: "言語",
  lbl_request_feature: "新規のリクエスト",
  lbl_feature: "特徴",
  lbl_settings_cutomise: "アプリをカスタマイズする",
  feature_request: "要件を説明してください",
  submit: "参加する",
  lbl_history: "レポート",
  monthly_budget: "月々の予算",
};
