import 'package:budgetplanner/utils/string_constants.dart';

const ru = {
  total_income: "Доход",
  total_expense: "Расходы",
  total_balance: "Остаток средств",
  recent_transaction: "Недавние транзакции",
  homeTab: "Дом",
  transactionTab: "Сделка",
  addTab: "Добавлять",
  budgetTab: "Бюджет",
  settingsTab: "Настройки",
  yesterday: "Вчера",
  today: "Сегодня",
  update_your_daily: "Ежедневно обновляйте",
  update: "Обновлять",
  lbl_trx_not_updated: "Ой !!! ... транзакция не обновлена!",
  lbl_trx_updated: "Транзакция успешно обновлена!",
  lbl_income_source: "Пожалуйста, выберите источник расходов",
  lbl_trx_cancelled: "Ой !!! ... транзакция отменена!",
  lbl_trx_success: "Транзакция успешно завершена!",
  lbl_amount_error: "Пожалуйста, введите сумму",
  lbl_notes_error: "Примечания должны состоять из 6 символов.",
  transactionEntry: "Добавить транзакцию",
  addExpense: "Добавить расходы",
  select_expense_category: "На что вы тратите?",
  amount: "Количество",
  notes: "Заметки",
  select_expense_source: "Выберите источник расходов",
  expense_type: "Тип расходов",
  want_or_need: "Хочу/Нужно",
  recurrance: "Повторение",
  addIncome: "Добавить доход",
  select_income_source: "Выберите источник дохода",
  plan_month: "Планируйте свой ежемесячный",
  addBudget: "Добавить бюджет",
  select_budget_category: "Выберите категорию бюджета",
  monthName: "Название месяца",
  update_plan_month: "Обновляйте ежемесячно",
  updateBudget: "Обновить бюджет",
  lbl_budget_not_update: "Ой !!! ... бюджет не обновляется!",
  lbl_budget_update: "Бюджет успешно обновлен!",
  lbl_budget_not_delete: "Ой !!! ... бюджет не удален!",
  lbl_budget_delete_success: "Удалено успешно!",
  lbl_budget_not_saved: "Ой !!! ... Бюджет не сохранен",
  lbl_budget_save_success: "Бюджет успешно сохранен!",
  lbl_select_budget_cat: "Выберите категорию бюджета",
  lbl_income_source_error: "Пожалуйста, выберите источник дохода",
  lbl_trx_not_delete: "Ой !!! ... транзакция не удалена!",
  //new translation
  lbl_no_budget: "Деньги заканчиваются каждый месяц",
  desc_no_budget:
      "Пора начать следить за тем, куда идет каждый доллар, и укреплять дисциплину для достижения своих финансовых целей.",
  lbl_add_one: "Добавить одну",
  lbl_no_transaction: "Всегда записывайте свою транзакцию",
  desc_no_transaction:
      "Это делает вас финансово дисциплинированным и укрепляет ваше финансовое здоровье.",
  lbl_config_laguage: "Настройте свой регион",
  lbl_language: "Язык",
  lbl_request_feature: "Запрос на новый",
  lbl_feature: "Характерная черта",
  lbl_settings_cutomise: "Настройте свое приложение",
  feature_request: "Пожалуйста, объясните свои требования",
  submit: "подавать",
  lbl_history: "Отчеты",
  monthly_budget: "Месячный бюджет",
};
