import 'package:budgetplanner/utils/string_constants.dart';

const ta = {
  total_income: "வருமானம்",
  total_expense: "செலவு",
  total_balance: "இருப்பு",
  recent_transaction: "சமீபத்திய பரிவர்த்தனைகள்",
  homeTab: "வீடு",
  transactionTab: "பரிவர்த்தனை",
  addTab: "கூட்டு",
  budgetTab: "பட்ஜெட்",
  settingsTab: "அமைப்புகள்",
  yesterday: "நேற்று",
  today: "இன்று",
  update_your_daily: "உங்கள் தினசரி புதுப்பிக்கவும்",
  update: "புதுப்பிப்பு",
  lbl_trx_not_updated: "அச்சச்சோ !!! ... பரிவர்த்தனை புதுப்பிக்கப்படவில்லை!",
  lbl_trx_updated: "பரிவர்த்தனை வெற்றிகரமாக புதுப்பிக்கப்பட்டது!",
  lbl_income_source: "செலவு மூலத்தைத் தேர்ந்தெடுக்கவும்",
  lbl_trx_cancelled: "அச்சச்சோ !!! ... பரிவர்த்தனை ரத்து செய்யப்பட்டது!",
  lbl_trx_success: "பரிவர்த்தனை வெற்றிகரமாக முடிந்தது!",
  lbl_amount_error: "தொகையை உள்ளிடவும்",
  lbl_notes_error: "குறிப்புகள் 6 எழுத்துகளைக் கொண்டிருக்க வேண்டும்",
  transactionEntry: "பரிவர்த்தனை சேர்க்கவும்",
  addExpense: "செலவு சேர்க்கவும்",
  select_expense_category: "நீங்கள் எதற்காக செலவு செய்கிறீர்கள்?",
  amount: "தொகை",
  notes: "குறிப்புகள்",
  select_expense_source: "செலவு மூலத்தைத் தேர்ந்தெடுக்கவும்",
  expense_type: "செலவு வகை",
  want_or_need: "வேண்டும்/தேவை",
  recurrance: "மறுநிகழ்வு",
  addIncome: "வருமானத்தைச் சேர்க்கவும்",
  select_income_source: "வருமான மூலத்தைத் தேர்ந்தெடுக்கவும்",
  plan_month: "உங்கள் மாதாந்திரத்தைத் திட்டமிடுங்கள்",
  addBudget: "பட்ஜெட்டைச் சேர்க்கவும்",
  select_budget_category: "பட்ஜெட் வகையைத் தேர்ந்தெடுக்கவும்",
  monthName: "மாதத்தின் பெயர்",
  update_plan_month: "உங்கள் மாதாந்திரத்தைப் புதுப்பிக்கவும்",
  updateBudget: "புதுப்பிப்பு பட்ஜெட்",
  lbl_budget_not_update: "அச்சச்சோ !!! ... பட்ஜெட் புதுப்பிக்கப்படவில்லை!",
  lbl_budget_update: "பட்ஜெட் வெற்றிகரமாக புதுப்பிக்கப்பட்டது!",
  lbl_budget_not_delete: "அச்சச்சோ !!! ... பட்ஜெட் நீக்கப்படவில்லை!",
  lbl_budget_delete_success: "வெற்றிகரமாக நீக்கப்பட்டது!",
  lbl_budget_not_saved: "அச்சச்சோ !!! ... பட்ஜெட் சேமிக்கப்படவில்லை",
  lbl_budget_save_success: "பட்ஜெட் வெற்றிகரமாக சேமிக்கப்பட்டது!",
  lbl_select_budget_cat: "பட்ஜெட் வகையைத் தேர்ந்தெடுக்கவும்",
  lbl_income_source_error: "வருமான ஆதாரத்தைத் தேர்ந்தெடுக்கவும்",
  lbl_trx_not_delete: "அச்சச்சோ !!! ... பரிவர்த்தனை நீக்கப்படவில்லை!",
};
